### PR TITLE
made it await then use .then

### PR DESCRIPTION
**Pull request by aditya1rawat**
cleaner

### CODE REVIEW

**Comment by aditya1rawat** [comment]
actually, i might have used await wrong. i don't have deno atm and im at school, could you check for me @KhushrajRathod ?

Thanks!

**Comment by safinsingh** [comment]
the braces around r.json() may be omitted btw

**Comment by safinsingh** [comment]
also await fetch not await(fetch

**Comment by aditya1rawat** [comment]
Yeah my bad. I was at school between periods writing this. Will fix. Or i think you have the option of fixing it too right? If you can make a or to my fork or smth. Sorry I'm going home atm and traffic is massive

**Comment by safinsingh** [comment]
empty catch body :// at least `console.error('something bad happend')`

**Comment by khrj** [comment]
@safinsingh Okay ig, its a script and not really a long running server -- You could always retry. But I'll put that in so you know what went wrong

**Comment by khrj** [comment]
Also @safinsingh @aditya1rawat add yourselves to the webring!

**Comment by safinsingh** [comment]
will do!

**Pull request merged**
